//! Runtime-side asset discovery: enumerate locally installed TTS voices,
//! TTS backends, STT engines, and the languages that result from them.
//!
//! Pure filesystem inspection, no network access. The GUI (and any other
//! caller) uses this to populate pickers — "what can the user choose right
//! now, given what's installed on this machine".
//!
//! Sources:
//! - `models/tts/mlx/voices.manifest.json` (generated by `make mlx-manifest`)
//!   plus `models/tts/mlx/voices/*.safetensors` (files that actually exist).
//! - `models/tts/mlx/kokoro-v1_0.safetensors` for MLX backend availability.
//! - `[stt.whisper].model_path` for Whisper availability.
//! - Apple SFSpeechRecognizer is always listed on macOS (helper is lazy).

use std::path::{Path, PathBuf};

/// Voice gender hint surfaced in the UI. `Unknown` keeps the picker
/// functional when a future voice id doesn't match the prefix convention.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Gender {
    Female,
    Male,
    Unknown,
}

impl Gender {
    fn parse(s: &str) -> Self {
        match s {
            "female" | "f" | "F" => Gender::Female,
            "male" | "m" | "M" => Gender::Male,
            _ => Gender::Unknown,
        }
    }
}

/// A locally installed TTS voice.
#[derive(Debug, Clone)]
pub struct VoiceInfo {
    /// Model-specific id, e.g. "if_sara".
    pub id: String,
    /// Human-readable name, e.g. "Sara".
    pub display: String,
    /// BCP-47 locale, e.g. "it-IT".
    pub lang: String,
    pub gender: Gender,
    /// Backend id this voice belongs to, e.g. "mlx".
    pub backend: String,
}

/// A TTS backend and whether it's usable right now.
#[derive(Debug, Clone)]
pub struct TtsBackend {
    pub id: String,
    pub name: String,
    pub available: bool,
    /// Human-readable reason when `available` is false.
    pub reason: Option<String>,
}

/// An STT engine and whether it's usable right now.
#[derive(Debug, Clone)]
pub struct SttEngine {
    pub id: String,
    pub name: String,
    pub available: bool,
    pub reason: Option<String>,
}

/// A language derived from the installed voices / engines.
#[derive(Debug, Clone)]
pub struct LangInfo {
    /// BCP-47 tag, e.g. "it-IT".
    pub bcp47: String,
    /// Localized name, e.g. "Italiano".
    pub display: String,
    pub has_tts: bool,
    pub has_stt: bool,
}

/// Where to look for model assets. Constructed from the running config so
/// the same Discovery works whether the app was launched from a source
/// checkout (`models/…`) or from a `.app` bundle (`Contents/Resources/models/…`).
#[derive(Debug, Clone)]
pub struct Discovery {
    mlx_model_dir: PathBuf,
    whisper_model_path: Option<PathBuf>,
}

impl Discovery {
    /// Build a Discovery from explicit asset paths.
    pub fn new(mlx_model_dir: impl Into<PathBuf>, whisper_model_path: Option<PathBuf>) -> Self {
        Self {
            mlx_model_dir: mlx_model_dir.into(),
            whisper_model_path,
        }
    }

    /// Enumerate TTS voices installed for the given backend.
    ///
    /// Currently only `"mlx"` returns entries; unknown backends yield an
    /// empty list (so a future ONNX path can be added without breaking callers).
    pub fn list_voices(&self, backend: &str) -> Vec<VoiceInfo> {
        match backend {
            "mlx" => self.list_mlx_voices(),
            _ => Vec::new(),
        }
    }

    fn list_mlx_voices(&self) -> Vec<VoiceInfo> {
        let voices_dir = self.mlx_model_dir.join("voices");
        let manifest = ManifestEntries::load(&self.mlx_model_dir.join("voices.manifest.json"));

        let mut out = Vec::new();
        let Ok(read) = std::fs::read_dir(&voices_dir) else {
            return out;
        };
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("safetensors") {
                continue;
            }
            let Some(id) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            let info = match manifest.find(id) {
                Some(m) => VoiceInfo {
                    id: m.id.clone(),
                    display: m.display.clone(),
                    lang: m.lang.clone(),
                    gender: Gender::parse(&m.gender),
                    backend: "mlx".to_string(),
                },
                None => derive_from_id(id),
            };
            out.push(info);
        }
        out.sort_by(|a, b| a.lang.cmp(&b.lang).then(a.id.cmp(&b.id)));
        out
    }

    /// List all known TTS backends with availability. Only `mlx` is
    /// enumerated for now — ONNX lands here when we re-enable it.
    pub fn list_tts_backends(&self) -> Vec<TtsBackend> {
        let mlx_weights = self.mlx_model_dir.join("kokoro-v1_0.safetensors");
        let mlx_avail = mlx_weights.is_file();
        vec![TtsBackend {
            id: "mlx".to_string(),
            name: "Kokoro (MLX, Apple Silicon)".to_string(),
            available: mlx_avail,
            reason: if mlx_avail {
                None
            } else {
                Some(format!("weights missing at {}", mlx_weights.display()))
            },
        }]
    }

    /// List all known STT engines with availability.
    pub fn list_stt_engines(&self) -> Vec<SttEngine> {
        let mut out = Vec::new();

        // Apple STT is OS-provided: listed only on macOS. The helper is
        // compiled + launched lazily, so we don't verify the binary here.
        if cfg!(target_os = "macos") {
            out.push(SttEngine {
                id: "apple".to_string(),
                name: "Apple Speech".to_string(),
                available: true,
                reason: None,
            });
        }

        let whisper_avail = self
            .whisper_model_path
            .as_deref()
            .map(Path::is_file)
            .unwrap_or(false);
        let whisper_reason = if whisper_avail {
            None
        } else {
            Some(match &self.whisper_model_path {
                Some(p) => format!("ggml model missing at {}", p.display()),
                None => "no whisper model_path configured".to_string(),
            })
        };
        out.push(SttEngine {
            id: "whisper".to_string(),
            name: "Whisper (offline)".to_string(),
            available: whisper_avail,
            reason: whisper_reason,
        });

        out
    }

    /// List BCP-47 languages that the user can pick. A language shows up
    /// if there's at least one installed voice for it. `has_stt` is true
    /// whenever any STT engine is available — both Apple and Whisper are
    /// multilingual, so we don't gate per language here.
    pub fn list_languages(&self) -> Vec<LangInfo> {
        let voices = self.list_mlx_voices();
        let stt_any = self.list_stt_engines().iter().any(|e| e.available);

        let mut by_lang: std::collections::BTreeMap<String, LangInfo> = Default::default();
        for v in voices {
            by_lang.entry(v.lang.clone()).or_insert_with(|| LangInfo {
                bcp47: v.lang.clone(),
                display: language_display(&v.lang).to_string(),
                has_tts: true,
                has_stt: stt_any,
            });
        }
        by_lang.into_values().collect()
    }
}

// ──────────────────────────────────────────────────────────────────────
// Manifest parsing
// ──────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default)]
struct ManifestEntries {
    entries: Vec<ManifestEntry>,
}

#[derive(Debug, Clone)]
struct ManifestEntry {
    id: String,
    display: String,
    lang: String,
    gender: String,
}

impl ManifestEntries {
    fn load(path: &Path) -> Self {
        let Ok(bytes) = std::fs::read(path) else {
            return Self::default();
        };
        let Ok(v) = serde_json::from_slice::<serde_json::Value>(&bytes) else {
            log::warn!(
                "discovery: voices.manifest.json at {} is not valid JSON, ignoring",
                path.display()
            );
            return Self::default();
        };
        let Some(arr) = v.get("voices").and_then(|x| x.as_array()) else {
            return Self::default();
        };
        let entries = arr
            .iter()
            .filter_map(|item| {
                let id = item.get("id")?.as_str()?.to_string();
                let display = item.get("display")?.as_str()?.to_string();
                let lang = item.get("lang")?.as_str()?.to_string();
                let gender = item
                    .get("gender")
                    .and_then(|x| x.as_str())
                    .unwrap_or("unknown")
                    .to_string();
                Some(ManifestEntry {
                    id,
                    display,
                    lang,
                    gender,
                })
            })
            .collect();
        Self { entries }
    }

    fn find(&self, id: &str) -> Option<&ManifestEntry> {
        self.entries.iter().find(|e| e.id == id)
    }
}

// ──────────────────────────────────────────────────────────────────────
// Fallbacks when a voice isn't in the manifest — uses the Kokoro voice-id
// convention `{lang_char}{gender_char}_{name}` so an install that's out
// of sync with the manifest still shows something sensible in the UI.
// ──────────────────────────────────────────────────────────────────────

fn derive_from_id(id: &str) -> VoiceInfo {
    let (prefix, name) = id.split_once('_').unwrap_or((id, ""));
    let mut chars = prefix.chars();
    let lang = match chars.next() {
        Some('a') => "en-US",
        Some('b') => "en-GB",
        Some('i') => "it-IT",
        Some('j') => "ja-JP",
        Some('z') => "zh-CN",
        Some('e') => "es-ES",
        Some('f') => "fr-FR",
        Some('h') => "hi-IN",
        Some('p') => "pt-BR",
        _ => "und",
    };
    let gender = match chars.next() {
        Some('f') => Gender::Female,
        Some('m') => Gender::Male,
        _ => Gender::Unknown,
    };
    let display = capitalize(name);
    VoiceInfo {
        id: id.to_string(),
        display,
        lang: lang.to_string(),
        gender,
        backend: "mlx".to_string(),
    }
}

fn capitalize(s: &str) -> String {
    let mut it = s.chars();
    match it.next() {
        Some(c) => c.to_uppercase().collect::<String>() + it.as_str(),
        None => String::new(),
    }
}

fn language_display(bcp47: &str) -> &'static str {
    match bcp47 {
        "en-US" => "English (US)",
        "en-GB" => "English (UK)",
        "it-IT" => "Italiano",
        "ja-JP" => "日本語",
        "zh-CN" => "中文",
        "es-ES" => "Español",
        "fr-FR" => "Français",
        "hi-IN" => "हिन्दी",
        "pt-BR" => "Português",
        _ => "",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn tmpdir() -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let n = COUNTER.fetch_add(1, Ordering::SeqCst);
        let dir = std::env::temp_dir().join(format!(
            "marginalia-discovery-{}-{n}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn write_voice(dir: &Path, id: &str) {
        let voices = dir.join("voices");
        fs::create_dir_all(&voices).unwrap();
        fs::write(voices.join(format!("{id}.safetensors")), b"stub").unwrap();
    }

    #[test]
    fn derive_italian_female() {
        let v = derive_from_id("if_sara");
        assert_eq!(v.lang, "it-IT");
        assert_eq!(v.gender, Gender::Female);
        assert_eq!(v.display, "Sara");
    }

    #[test]
    fn derive_italian_male() {
        let v = derive_from_id("im_nicola");
        assert_eq!(v.lang, "it-IT");
        assert_eq!(v.gender, Gender::Male);
    }

    #[test]
    fn discovery_lists_only_files_present() {
        let dir = tmpdir();
        fs::write(dir.join("kokoro-v1_0.safetensors"), b"stub").unwrap();
        write_voice(&dir, "if_sara");
        write_voice(&dir, "im_nicola");

        let d = Discovery::new(&dir, None);
        let voices = d.list_voices("mlx");
        assert_eq!(voices.len(), 2);
        assert!(voices.iter().any(|v| v.id == "if_sara"));

        let backends = d.list_tts_backends();
        assert!(backends.iter().any(|b| b.id == "mlx" && b.available));
    }

    #[test]
    fn manifest_overrides_derivation() {
        let dir = tmpdir();
        write_voice(&dir, "xf_custom");
        fs::write(
            dir.join("voices.manifest.json"),
            r#"{
              "schema_version": 1,
              "voices": [
                {"id": "xf_custom", "display": "Custom", "lang": "xx-YY", "gender": "female"}
              ]
            }"#,
        )
        .unwrap();
        let d = Discovery::new(&dir, None);
        let v = &d.list_voices("mlx")[0];
        assert_eq!(v.display, "Custom");
        assert_eq!(v.lang, "xx-YY");
    }

    #[test]
    fn tts_backend_unavailable_without_weights() {
        let dir = tmpdir();
        let d = Discovery::new(&dir, None);
        let backends = d.list_tts_backends();
        let mlx = backends.iter().find(|b| b.id == "mlx").unwrap();
        assert!(!mlx.available);
        assert!(mlx.reason.is_some());
    }

    #[test]
    fn whisper_availability_tracks_file() {
        let dir = tmpdir();
        let whisper = dir.join("ggml-small.bin");
        let d = Discovery::new(&dir, Some(whisper.clone()));
        let engines = d.list_stt_engines();
        assert!(!engines.iter().find(|e| e.id == "whisper").unwrap().available);

        fs::write(&whisper, b"stub").unwrap();
        let d = Discovery::new(&dir, Some(whisper));
        let engines = d.list_stt_engines();
        assert!(engines.iter().find(|e| e.id == "whisper").unwrap().available);
    }
}
