"""Persistence ports."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from marginalia_core.domain.document import Document
from marginalia_core.domain.note import VoiceNote
from marginalia_core.domain.reading_session import ReadingSession
from marginalia_core.domain.rewrite import RewriteDraft
from marginalia_core.domain.search import SearchQuery, SearchResult


class DocumentRepository(Protocol):
    """Store and query ingested documents."""

    def ensure_schema(self) -> None: ...
    def save_document(self, document: Document) -> None: ...
    def get_document(self, document_id: str) -> Document | None: ...
    def list_documents(self) -> Sequence[Document]: ...
    def search_documents(self, query: SearchQuery | str) -> Sequence[SearchResult]: ...


class SessionRepository(Protocol):
    """Store and query reading sessions."""

    def ensure_schema(self) -> None: ...
    def save_session(self, session: ReadingSession) -> None: ...
    def get_active_session(self) -> ReadingSession | None: ...
    def deactivate_stale_sessions(self, *, max_inactive_hours: int) -> int: ...


class NoteRepository(Protocol):
    """Store and search anchored notes."""

    def ensure_schema(self) -> None: ...
    def save_note(self, note: VoiceNote) -> None: ...
    def list_notes_for_document(self, document_id: str) -> Sequence[VoiceNote]: ...
    def search_notes(self, query: SearchQuery | str) -> Sequence[SearchResult]: ...


class RewriteDraftRepository(Protocol):
    """Store rewrite drafts for later review."""

    def ensure_schema(self) -> None: ...
    def save_draft(self, draft: RewriteDraft) -> None: ...
    def list_drafts_for_document(self, document_id: str) -> Sequence[RewriteDraft]: ...
